"""
controls/live_controllers.py -- admission-only controllers for the live A5000
closed-loop experiment (power limits are root-only on node-d1, so the ONLY
actuator is the admission gate: max requests in flight).

Why admission can control power/energy on this GPU: the A5000s on node-d1 are
admin-capped at 100 W (TDP 230 W) and idle at ~61 W with a model loaded; any
running batch pins the GPU at the cap (SM clock ~210 MHz), so
      P(t) ~= P_idle            if nothing is running
             ~= P_busy (~100 W)  if >= 1 request is running.
Average power over a window is therefore set by the *busy duty cycle*, and
energy per token = P_busy / throughput(n) falls steeply with batch size n. The
controller's levers are (i) closing the gate so the batch drains and the GPU
idles (budget), and (ii) holding arrivals to release them as bigger batches
(energy), subject to TTFT/TPOT SLOs. This is non-work-conserving batching --
useless on the uncapped H200/B200 in the fleet sim, first-order here.

Every controller implements  reset(cfg)  and  act(obs) -> int max_in_flight.
obs (built once per 1 s tick by live_load.py or by simulate_live below):
    t, dt, q (waiting), n_run (in flight), ages (waiting ages, s, oldest first),
    run_done_tok (tokens already generated by each running request),
    p_1s, p_10s (mean measured power), budget, budget_future (N), arr_hist,
    tok_tick, tpot_tick
cfg: dict(table=..., p_idle, p_busy, gen_mean, gen_cap, slo_ttft, slo_tpot,
          m_max, horizon, budget_window)
"""
import math
import time
from collections import deque

import numpy as np


# ----------------------------------------------------------------------------
# plant knowledge: throughput table  n -> tokens/s  (from sweep / staircase)
# ----------------------------------------------------------------------------
# Qwen2.5-3B alpaca on the 100-W-capped A5000 (logs/A5000, closed loop, 45 s
# windows): n -> aggregate tok/s. Busy power ~99.6 W at every n; idle 61.4 W.
DEFAULT_TABLE_3B = {1: 21.4, 4: 145.5, 16: 476.7, 64: 1247.4}


class Throughput:
    """log-log interpolation of aggregate tokens/s vs running batch n."""

    def __init__(self, table):
        ks = sorted(table)
        self.n = np.log(np.array(ks, float))
        self.v = np.log(np.array([table[k] for k in ks], float))
        self.nmax = ks[-1]

    def __call__(self, n):
        if n <= 0:
            return 0.0
        x = math.log(max(n, 1.0))
        if x >= self.n[-1]:           # beyond table: extrapolate with last slope, capped
            s = (self.v[-1] - self.v[-2]) / (self.n[-1] - self.n[-2])
            return float(math.exp(self.v[-1] + min(s, 1.0) * (x - self.n[-1])))
        return float(math.exp(np.interp(x, self.n, self.v))) * (n / max(n, 1.0))


def default_cfg(**kw):
    c = dict(table=DEFAULT_TABLE_3B, p_idle=61.4, p_busy=99.6, gen_mean=235.0,
             gen_cap=256, slo_ttft=5.0, slo_tpot=0.25, m_max=64, horizon=20,
             budget_window=10)
    c.update(kw)
    return c


_MU_CACHE = {}


def solve_mu(gen_mean, gen_cap):
    """mu such that E[min(Exp(mu), cap)] = gen_mean."""
    key = (round(gen_mean, 3), gen_cap)
    if key not in _MU_CACHE:
        lo, hi = 1.0, 1e5
        for _ in range(60):
            mu = 0.5 * (lo + hi)
            m = mu * (1 - math.exp(-gen_cap / mu))
            lo, hi = (mu, hi) if m < gen_mean else (lo, mu)
        _MU_CACHE[key] = mu
    return _MU_CACHE[key]


def residual_tokens(g_done, gen_mean, gen_cap):
    """E[G - g | G > g] for G ~ min(Exp(mu), cap) (mu solved for the mean)."""
    mu = solve_mu(gen_mean, gen_cap)
    rem_cap = gen_cap - g_done
    if rem_cap <= 0:
        return 1.0
    # memoryless below the cap: E[min(Exp(mu), rem_cap)]
    return max(1.0, mu * (1 - math.exp(-rem_cap / mu)))


# ----------------------------------------------------------------------------
# controllers
# ----------------------------------------------------------------------------
class LiveController:
    name = "base"

    def reset(self, cfg):
        self.cfg = cfg
        self.thr = Throughput(cfg["table"])
        self.solve_times = []

    def info(self):
        return {}


class StaticGate(LiveController):
    """Work-conserving fixed concurrency cap (what a default server does)."""

    def __init__(self, m=64):
        self.m = m
        self.name = f"static{m}"

    def act(self, obs):
        return self.m


class PIPowerGate(LiveController):
    """PI on the admission cap tracking the power budget on a moving window,
    with a queue-delay term that re-opens the gate when there is headroom.
    Classic feedback baseline (Hellerstein-style), no model, no preview."""
    name = "PI"

    def __init__(self, kp=6.0, ki=3.0, margin=0.97, q_gain=4.0):
        self.kp, self.ki, self.margin, self.qg = kp, ki, margin, q_gain

    def reset(self, cfg):
        super().reset(cfg)
        self.m = float(cfg["m_max"])
        self.e_prev = 0.0

    def act(self, obs):
        c = self.cfg
        span = max(c["p_busy"] - c["p_idle"], 1.0)
        e = (self.margin * obs["budget"] - obs["p_10s"]) / span
        wait = obs["ages"][0] if obs["ages"] else 0.0
        if e > 0:
            e += self.qg * max(0.0, wait / c["slo_ttft"] - 0.5) * 0.1
        self.m += c["m_max"] * (self.kp * (e - self.e_prev) + self.ki * e) * 0.1
        self.m = float(np.clip(self.m, 0, c["m_max"]))
        self.e_prev = e
        return int(round(self.m))

    def info(self):
        return dict(m_float=self.m)


class POLCAGate(LiveController):
    """Reactive two-threshold throttling on last second's measured power
    (POLCA-style): above t_hi*budget stop admitting and shrink the cap; below
    t_lo*budget re-open in steps."""
    name = "POLCA"

    def __init__(self, t_hi=0.97, t_lo=0.85, step=8):
        self.t_hi, self.t_lo, self.step = t_hi, t_lo, step

    def reset(self, cfg):
        super().reset(cfg)
        self.m = cfg["m_max"]

    def act(self, obs):
        B = obs["budget"]
        if obs["p_1s"] > self.t_hi * B:
            self.m = int(obs["n_run"] // 2)
        elif obs["p_1s"] < self.t_lo * B:
            self.m = min(self.m + self.step, self.cfg["m_max"])
        return int(self.m)


class AdmissionMPC(LiveController):
    """Receding-horizon policy-search MPC over the admission gate.

    Each tick it rolls out a small family of gate policies over N seconds with
    the internal model (throughput table + busy/idle power + expected residual
    tokens of every running request + FIFO ages + EWMA arrival forecast +
    announced budget preview) and applies the first move of the cheapest:
        policy(theta, m, hold): release up to m in flight when
            q >= theta  or  oldest wait >= slo_ttft - lead   (batch accumulation)
        and never admit while the windowed power would exceed the budget.
    cost = energy + rho_q * (s of SLO-exceeding wait) + rho_b * (J over budget,
           on the budget_window moving average) + rho_t * TPOT excess
           + terminal backlog.  Online gain on P_busy (measured/predicted)."""
    name = "MPC"

    def __init__(self, thetas=(1, 4, 8, 16, 32, 48, 64), caps=(8, 16, 32, 64), lead=1.5,
                 rho_q=40.0, rho_b=500.0, rho_t=400.0, alpha=0.3, preview=True,
                 guards=("idle", "always"), modes=("ride", "cont", "sync")):
        self.thetas, self.caps, self.lead, self.guards = thetas, caps, lead, guards
        self.modes = modes
        self.rho_q, self.rho_b, self.rho_t, self.alpha = rho_q, rho_b, rho_t, alpha
        self.preview = preview

    def reset(self, cfg):
        super().reset(cfg)
        self.lam = None
        self.p_hist = deque(maxlen=cfg["budget_window"])
        self.gain = 1.0
        self.last = None

    def _rollout(self, obs, lam, bud, theta, m, guard="idle", mode="cont"):
        c = self.cfg
        dt = obs["dt"]
        N = len(bud)
        ages = list(obs["ages"])
        run = [residual_tokens(g, c["gen_mean"], c["gen_cap"]) for g in obs["run_done_tok"]]
        ph = list(self.p_hist)
        W = c["budget_window"]
        E = qpen = bpen = tpen = 0.0
        acc = 0.0
        first_m = None
        pb = c["p_busy"] * self.gain
        for j in range(N):
            # arrivals (fluid, as fractional requests at age 0)
            acc += lam * dt
            while acc >= 1.0:
                ages.append(0.0)
                acc -= 1.0
            oldest = ages[0] if ages else 0.0
            release = len(ages) >= theta or (ages and oldest >= c["slo_ttft"] - self.lead)
            # 'sync' = batch-synchronous: only start a new batch once the GPU has
            # drained, so the arrivals accumulated during a batch plus the hold
            # form the next batch and the GPU idles in between (duty cycling)
            if mode == "sync" and run:
                release = False
            # 'ride' = admit freely while a batch is running (power is already
            # pinned at the cap, extra requests ride for free) and hold only
            # while idle until theta requests / the TTFT deadline accumulate
            if mode == "ride" and run:
                release = True
            # budget guard: do not start new work if the window would overshoot
            win = (sum(ph[-(W - 1):]) + pb) / min(len(ph) + 1, W) if W > 1 else pb
            # (starting from idle costs P_busy - P_idle; admitting while busy only
            #  extends the busy period, so the 'always' guard stops admissions
            #  whenever the window is over budget, letting the batch drain)
            if win > bud[j] and (guard == "always" or not run):
                release = False
            mm = m if release else len(run)
            k = 0
            while ages and len(run) < mm:
                ages.pop(0)
                run.append(float(c["gen_mean"]))
                k += 1
            if first_m is None:
                # hold => 0 (admit nothing until next tick; a cap equal to n_run
                # would silently refill as requests finish)
                first_m = m if release else 0
            n = len(run)
            if n:
                r = self.thr(n) / n * dt                     # tokens per request this step
                busy = min(1.0, max(run) / max(r, 1e-9))
                run = [x - r for x in run if x - r > 0]
                p = c["p_idle"] + (pb - c["p_idle"]) * busy
                tp = n / max(self.thr(n), 1e-9)
                tpen += max(0.0, tp - c["slo_tpot"]) * n
            else:
                p = c["p_idle"]
            E += p * dt
            ph.append(p)
            w = sum(ph[-W:]) / min(len(ph), W)
            bpen += max(0.0, w - bud[j]) * dt
            ages = [a + dt for a in ages]
            qpen += sum(1.0 for a in ages if a > c["slo_ttft"]) * dt
        term = len(ages) * c["gen_mean"] / max(self.thr(c["m_max"]), 1.0) * pb
        cost = E + self.rho_q * qpen + self.rho_b * bpen + self.rho_t * tpen + term
        return cost, first_m

    def act(self, obs):
        t0 = time.perf_counter()
        c = self.cfg
        a = obs["arr_hist"][-1] / obs["dt"] if obs["arr_hist"] else 0.0
        self.lam = a if self.lam is None else self.alpha * a + (1 - self.alpha) * self.lam
        # online gain on busy power (the cap may drift: thermals, other tenants)
        if obs["n_run"] > 0 and obs["p_1s"] > c["p_idle"] + 5:
            self.gain = float(np.clip(0.9 * self.gain + 0.1 * obs["p_1s"] / c["p_busy"], 0.8, 1.2))
        self.p_hist.append(obs["p_1s"])
        N = c["horizon"]
        if self.preview and obs.get("budget_future") is not None and len(obs["budget_future"]):
            bud = list(obs["budget_future"][:N])
            bud += [bud[-1]] * (N - len(bud))
        else:
            bud = [obs["budget"]] * N
        best = (math.inf, c["m_max"], None)
        for md in self.modes:
            for g in self.guards:
                for th in self.thetas:
                    for m in self.caps:
                        if md != "sync" and th > m:
                            continue
                        cost, m0 = self._rollout(obs, self.lam, bud, th, m, g, md)
                        if cost < best[0]:
                            best = (cost, m0, (th, m, g, md))
        self.last = dict(cost=best[0], theta=best[2][0], cap=best[2][1], guard=best[2][2],
                         mode=best[2][3], lam=self.lam, gain=self.gain)
        self.solve_times.append(time.perf_counter() - t0)
        return int(best[1])

    def info(self):
        return dict(self.last or {})


def make_live_controller(name, **kw):
    if name.startswith("static"):
        return StaticGate(int(name[6:] or 64))
    return {"pi": PIPowerGate, "polca": POLCAGate, "mpc": AdmissionMPC}[name.lower()](**kw)


# ----------------------------------------------------------------------------
# CPU simulator of the capped A5000 (request level) -- for dry runs / offline eval
# ----------------------------------------------------------------------------
def mmpp_arrivals(T, lo, hi, dlo, dhi, seed):
    rng = np.random.default_rng(seed)
    t, state, out = 0.0, 0, []
    t_switch = rng.exponential(dlo)
    while t < T:
        lam = hi if state else lo
        t += rng.exponential(1.0 / lam)
        while t > t_switch:
            state = 1 - state
            t_switch += rng.exponential(dhi if state else dlo)
        out.append(t)
    return np.array([x for x in out if x < T])


def parse_schedule(s):
    """'100:90,80:60' -> [(W, dur), ...]"""
    return [(float(a), float(b)) for a, b in (p.split(":") for p in s.split(","))]


def budget_at(sched, t):
    acc = 0.0
    for w, d in sched:
        if t < acc + d:
            return w
        acc += d
    return sched[-1][0]


def simulate_live(ctrl, cfg, T=300, arrivals=None, budget_sched="100:300", seed=0,
                  gen_seed=1, dt_sim=0.01, true_table=None, p_busy_true=None):
    """Request-level simulation of the capped GPU driven by a live controller
    exactly as live_load.py drives it (1 s ticks). Returns metrics dict."""
    rng = np.random.default_rng(gen_seed)
    thr = Throughput(true_table or cfg["table"])
    pb = p_busy_true or cfg["p_busy"]
    sched = parse_schedule(budget_sched)
    arr = list(arrivals if arrivals is not None else mmpp_arrivals(T, 1.0, 3.5, 40, 12, seed))
    mu = solve_mu(cfg["gen_mean"], cfg["gen_cap"])
    waiting, running, done = deque(), [], []
    ctrl.reset(cfg)
    m = cfg["m_max"]
    t, next_tick = 0.0, 0.0
    ph, arr_hist, a_cnt, p_acc, p_n = deque(maxlen=10), [], 0, 0.0, 0
    tok_tick, E, P_log, B_log = 0, 0.0, [], []
    while t < T:
        while arr and arr[0] <= t:
            arr.pop(0)
            g = int(min(cfg["gen_cap"], max(1, rng.exponential(mu))))
            waiting.append(dict(t_arr=t, G=g))
            a_cnt += 1
        if t >= next_tick:
            p1 = p_acc / max(p_n, 1) if p_n else cfg["p_idle"]
            ph.append(p1)
            P_log.append(p1)
            B_log.append(budget_at(sched, t))
            arr_hist.append(a_cnt)
            a_cnt, p_acc, p_n = 0, 0.0, 0
            obs = dict(t=t, dt=1.0, q=len(waiting), n_run=len(running),
                       ages=[t - r["t_arr"] for r in waiting],
                       run_done_tok=[r["g"] for r in running], p_1s=p1,
                       p_10s=float(np.mean(ph)), budget=budget_at(sched, t),
                       budget_future=[budget_at(sched, t + k) for k in range(cfg["horizon"])],
                       arr_hist=arr_hist[-60:], tok_tick=tok_tick, tpot_tick=0.0)
            m = ctrl.act(obs)
            tok_tick = 0
            next_tick += 1.0
        while waiting and len(running) < m:
            r = waiting.popleft()
            r.update(t_adm=t, g=0.0, t_first=None)
            running.append(r)
        n = len(running)
        if n:
            rate = thr(n) / n * dt_sim
            for r in running:
                r["g"] += rate
                if r["t_first"] is None and r["g"] >= 1:
                    r["t_first"] = t
            fin = [r for r in running if r["g"] >= r["G"]]
            for r in fin:
                r["t_fin"] = t
                done.append(r)
            running = [r for r in running if r["g"] < r["G"]]
            tok_tick += rate * n
            p = pb
        else:
            p = cfg["p_idle"]
        E += p * dt_sim
        p_acc += p
        p_n += 1
        t += dt_sim
    ttft = np.array([r["t_first"] - r["t_arr"] for r in done if r["t_first"] is not None])
    tpot = np.array([(r["t_fin"] - r["t_first"]) / max(r["G"] - 1, 1) for r in done
                     if r["t_first"] is not None])
    toks = sum(r["G"] for r in done)
    P, B = np.array(P_log), np.array(B_log)
    P10 = np.convolve(P, np.ones(10) / 10, mode="full")[:len(P)]
    return dict(ctrl=ctrl.name, energy_kj=E / 1e3, tokens=toks, j_per_tok=E / max(toks, 1),
                completed=len(done), left=len(waiting) + len(running),
                ttft_p50=float(np.median(ttft)) if len(ttft) else float("nan"),
                ttft_p99=float(np.percentile(ttft, 99)) if len(ttft) else float("nan"),
                ttft_viol=float(np.mean(ttft > cfg["slo_ttft"])) if len(ttft) else float("nan"),
                tpot_p50=float(np.median(tpot)) if len(tpot) else float("nan"),
                tpot_viol=float(np.mean(tpot > cfg["slo_tpot"])) if len(tpot) else float("nan"),
                bviol_1s=float(np.mean(P > B * 1.01)), bviol_10s=float(np.mean(P10 > B * 1.01)),
                over_j=float(np.sum(np.maximum(P10 - B, 0))),
                solve_ms_mean=1e3 * float(np.mean(ctrl.solve_times)) if ctrl.solve_times else 0.0,
                solve_ms_max=1e3 * float(np.max(ctrl.solve_times)) if ctrl.solve_times else 0.0)
